module.exports.eventTypes = {
  HACKATHON_CREATED: "HACKATHON_CREATED",
  HACKATHON_PUBLISHED: "HACKATHON_PUBLISHED",
  HACKATHON_UNPUBLISHED: "HACKATHON_UNPUBLISHED",
  HACKATHON_REGISTRATION_OPEN: "HACKATHON_REGISTRATION_OPEN",
  HACKATHON_REGISTRATION_CLOSED: "HACKATHON_REGISTRATION_CLOSED",
  HACKATHON_DETAILS_UPDATED: "HACKATHON_DETAILS_UPDATED",
}

module.exports.commandTypes = {
  CREATE_HACKATHON: "CREATE_HACKATHON",
  PUBLISH_HACKATHON: "PUBLISH_HACKATHON",
  UNPUBLISH_HACKATHON: "UNPUBLISH_HACKATHON",
  UPDATE_HACKATHON_DETAILS: "UPDATE_HACKATHON_DETAILS",
  OPEN_HACKATHON_REGISTRATION: "OPEN_HACKATHON_REGISTRATION",
  CLOSE_HACKATHON_REGISTRATION: "CLOSE_HACKATHON_REGISTRATION",
}